name: myenv  # Name of the environment
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas=1.5.0
  - numpy=1.23.0
  - scikit-learn=1.1.0
  - seaborn=0.11.2
  - matplotlib=3.5.2
  - plotly=5.5.0
  - xgboost=1.6.0
