name: Run Cement Strength Prediction Model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Replace with the specific Python version if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: |
        python cement_strength_prediction_model.py

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: model-results
        path: results/  # Adjust this path to where your script saves outputs
